import { act, cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import WarController from "../../src/client/games/tiny-bloody-war/controller";
import type { WarPhoneFrame } from "../../src/client/games/tiny-bloody-war/host";

const you={id:"alex",name:"Alex",seat:2,color:"#52e0b0",connected:true,ready:true,awayAt:null};
const frame:WarPhoneFrame={t:"warState",phase:"practice",role:"soldier",team:0,interactive:true,status:"PRACTICE",health:3,maxHealth:3,remaining:5,battle:1,wins:[0,0],uneven:false};
const rect=()=>({left:0,top:0,right:300,bottom:300,width:300,height:300,x:0,y:0,toJSON(){}});
describe("Tiny Bloody War controller",()=>{beforeEach(()=>vi.useFakeTimers());afterEach(()=>{cleanup();vi.runOnlyPendingTimers();vi.useRealTimers();vi.restoreAllMocks();});
  it("presents landscape resting-thumb controls, shape identity, role choice and sound",()=>{render(<WarController you={you} send={()=>undefined} connected last={frame}/>);expect(screen.getByRole("application",{name:"Move your fighter"})).toBeTruthy();expect(screen.getByRole("application",{name:"Aim and release to attack"})).toBeTruthy();expect(screen.getByText("RUST SQUARES")).toBeTruthy();expect(screen.getByRole("button",{name:/SHIELD/}).getAttribute("aria-pressed")).toBe("true");expect(screen.getByRole("button",{name:"Turn sound off"})).toBeTruthy();});
  it("coalesces movement at 20Hz and cancels all held input on blur",()=>{const send=vi.fn();render(<WarController you={you} send={send} connected last={frame}/>);send.mockClear();const move=screen.getByRole("application",{name:"Move your fighter"});Object.defineProperty(move,"getBoundingClientRect",{value:rect});Object.defineProperty(move,"setPointerCapture",{value:vi.fn()});fireEvent.pointerDown(move,{pointerId:1,clientX:100,clientY:100});fireEvent.pointerMove(move,{pointerId:1,clientX:178,clientY:100});act(()=>vi.advanceTimersByTime(50));expect(send).toHaveBeenLastCalledWith({moveX:1,moveY:0});fireEvent.blur(window);expect(send).toHaveBeenLastCalledWith({moveX:0,moveY:0});});
  it("fires on deliberate pointer release but cancellation never sends a release",()=>{const send=vi.fn();render(<WarController you={you} send={send} connected last={{...frame,phase:"live"}}/>);send.mockClear();const aim=screen.getByRole("application",{name:"Aim and release to attack"});Object.defineProperty(aim,"getBoundingClientRect",{value:rect});Object.defineProperty(aim,"setPointerCapture",{value:vi.fn()});fireEvent.pointerDown(aim,{pointerId:2,clientX:100,clientY:100});fireEvent.pointerMove(aim,{pointerId:2,clientX:178,clientY:100});fireEvent.pointerUp(aim,{pointerId:2});expect(send.mock.calls.some(([x])=>typeof (x as {release?:unknown}).release==="number")).toBe(true);send.mockClear();fireEvent.pointerDown(aim,{pointerId:3,clientX:100,clientY:100});fireEvent.pointerMove(aim,{pointerId:3,clientX:178,clientY:100});fireEvent.pointerCancel(aim,{pointerId:3});expect(send.mock.calls.some(([x])=>"release" in (x as object))).toBe(false);expect(send).toHaveBeenLastCalledWith({aiming:false});});
  it("selects only its own batch frame and labels uneven prototypes",()=>{render(<WarController you={you} send={()=>undefined} connected last={{t:"warStates",frames:{alex:{...frame,status:"OWN",uneven:true},rival:{...frame,status:"RIVAL"}}}}/>);expect(screen.getByText("OWN")).toBeTruthy();expect(screen.queryByText("RIVAL")).toBeNull();expect(screen.getByText("PLAYTEST · UNEVEN TEAMS")).toBeTruthy();});
  it("neutralizes on disconnect and requests a snapshot on mount",()=>{const send=vi.fn();const v=render(<WarController you={you} send={send} connected last={frame}/>);expect(send).toHaveBeenCalledWith({sync:true});v.rerender(<WarController you={you} send={send} connected={false} last={frame}/>);expect(screen.getByRole("alert").textContent).toContain("Movement and attack cancelled");});
});
