/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=/dev/null --include-runtime=false` (hash: e4723e55a1072bab57d0ec410c54dcb5)
interface __BaseEnv_Env {
	ROOM_CREATION_RATE_LIMITER: RateLimit;
	CONNECTION_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	Room: DurableObjectNamespace<import("./src/server/index").Room>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server/index");
		durableNamespaces: "Room";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
