import type { Player, RoundResult } from "../../../shared/protocol";
import type { GameHost, HostContext } from "../registry";
import { WarSound, isWarCue, type WarCue } from "./sound";

export const WAR_RULES = {
  practice: 6, runway: 10, battle: 90, battleFinish: 3, respawn: 3, protection: 2.4,
  moveSpeed: 205, soldierBrace: .48, archerDraw: .66, aimDeadZone: .32, minHold: .18,
  soldierHealth: 3, archerHealth: 2, thrustReach: 76, thrustRecovery: .52, arrowRecovery: .62,
  arrowSpeed: 510, objectiveRadius: 125, relocateAt: [30, 60], maxArrows: 24, maxParticles: 140,
} as const;

export type WarRole = "soldier" | "archer";
type Phase = "practice" | "countdown" | "live" | "battle-result" | "set-result";
export interface WarInput { moveX?: number; moveY?: number; aimX?: number; aimY?: number; aiming?: boolean; release?: number; cancel?: boolean; role?: WarRole; sync?: boolean }
export interface Fighter {
  id: string; name: string; seat: number; color: string; team: 0 | 1; role: WarRole; x: number; y: number; vx: number; vy: number;
  moveX: number; moveY: number; aimX: number; aimY: number; facing: number; aiming: boolean; aimHeld: number; lastRelease: number | null;
  health: number; deadFor: number; protectedFor: number; recovery: number; attackFor: number; connected: boolean;
  blocks: number; hits: number; contest: number; deaths: number;
}
interface Arrow { owner: string; team: 0 | 1; x: number; y: number; vx: number; vy: number; life: number }
interface Particle { x: number; y: number; vx: number; vy: number; life: number; color: string }
export interface WarState {
  fighters: Fighter[]; participantIds: Set<string>; arrows: Arrow[]; particles: Particle[]; phase: Phase; phaseTime: number; liveTime: number;
  battle: number; wins: [number, number]; scores: [number, number]; objectiveIndex: number; finished: boolean; reducedMotion: boolean;
  randomState: number; phoneClock: number; events: Array<{ cue: WarCue; to?: string }>; goFlash: number;
}
export interface WarPhoneFrame {
  t: "warState"; phase: Phase | "respawning" | "spectating"; role: WarRole; team: 0 | 1; interactive: boolean; status: string;
  health: number; maxHealth: number; remaining: number; battle: number; wins: [number, number]; uneven: boolean; cues?: WarCue[];
}
export interface WarPhoneFrames { t: "warStates"; frames: Record<string, WarPhoneFrame> }

const SITES = [{ x: 0, y: 0 }, { x: 420, y: -195 }, { x: -405, y: 205 }];
const OBSTACLES = [{x:-270,y:-235,w:190,h:48},{x:220,y:215,w:190,h:48},{x:-520,y:25,w:135,h:42},{x:385,y:-5,w:135,h:42}];
const TEAM = [{ color: "#c44735", light: "#ff725c", name: "RUST", shape: "■" }, { color: "#0799b8", light: "#43d9ee", name: "TIDE", shape: "▲" }];
const clamp = (n: number, lo: number, hi: number) => Math.max(lo, Math.min(hi, n));
const finite = (n: unknown) => typeof n === "number" && Number.isFinite(n) ? n : 0;
const healthFor = (role: WarRole) => role === "soldier" ? WAR_RULES.soldierHealth : WAR_RULES.archerHealth;
function rand(s: WarState) { s.randomState = (Math.imul(s.randomState, 1664525) + 1013904223) >>> 0; return s.randomState / 4294967296; }
function spawn(f: Fighter, protectedSpawn = false) { const row = Math.floor(f.seat / 2) % 5; f.x = f.team ? 690 : -690; f.y = (row - 2) * 118; f.vx = f.vy = 0; f.health = healthFor(f.role); f.deadFor = 0; f.protectedFor = protectedSpawn ? WAR_RULES.protection : 0; f.recovery = f.attackFor = 0; f.aiming = false; f.aimHeld = 0; f.facing = f.team ? Math.PI : 0; }
function makeFighter(p: Player, index: number): Fighter {
  const team = (index % 2) as 0 | 1; const role: WarRole = Math.floor(index / 2) % 2 ? "archer" : "soldier";
  const f: Fighter = { id:p.id,name:p.name,seat:p.seat,color:p.color,team,role,x:0,y:0,vx:0,vy:0,moveX:0,moveY:0,aimX:team?-1:1,aimY:0,facing:team?Math.PI:0,aiming:false,aimHeld:0,lastRelease:null,health:healthFor(role),deadFor:0,protectedFor:0,recovery:0,attackFor:0,connected:p.connected,blocks:0,hits:0,contest:0,deaths:0 };
  spawn(f); return f;
}
export function createWarState(players: Player[], seed: number, reducedMotion = false): WarState {
  return { fighters: players.map(makeFighter), participantIds:new Set(players.map(p=>p.id)), arrows:[],particles:[],phase:"practice",phaseTime:0,liveTime:0,battle:1,wins:[0,0],scores:[0,0],objectiveIndex:0,finished:false,reducedMotion,randomState:seed>>>0,phoneClock:0,events:[],goFlash:0 };
}
function emit(s: WarState, cue: WarCue, to?: string) { s.events.push({cue,to}); }
function particles(s: WarState, x:number,y:number,color:string,count:number) { if(s.reducedMotion)return; for(let i=0;i<count&&s.particles.length<WAR_RULES.maxParticles;i++){const a=rand(s)*Math.PI*2, speed=40+rand(s)*130;s.particles.push({x,y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,life:.18+rand(s)*.3,color});} }
function resetBattle(s: WarState) { s.scores=[0,0];s.objectiveIndex=0;s.liveTime=0;s.arrows=[];for(const f of s.fighters){spawn(f);f.moveX=f.moveY=0;} }
export function cancelWarInput(f: Fighter) { f.moveX=f.moveY=0; f.aiming=false; f.aimHeld=0; }
export function applyWarInput(s: WarState, id:string, value:unknown) {
  const f=s.fighters.find(x=>x.id===id); if(!f||f.deadFor>0||!value||typeof value!=="object"||Array.isArray(value))return;
  const d=value as WarInput;
  if(d.sync)return;
  if(d.role==="soldier"||d.role==="archer") { if((s.phase==="practice"||s.phase==="battle-result")&&f.role!==d.role){f.role=d.role;f.health=healthFor(f.role);} return; }
  if(d.cancel){f.aiming=false;f.aimHeld=0;f.moveX=f.moveY=0;return;}
  if(d.moveX!==undefined||d.moveY!==undefined){let x=finite(d.moveX),y=finite(d.moveY),m=Math.hypot(x,y);if(m>1){x/=m;y/=m;}f.moveX=x;f.moveY=-y;}
  if(d.aimX!==undefined||d.aimY!==undefined){let x=finite(d.aimX),y=-finite(d.aimY),m=Math.hypot(x,y);if(m>1){x/=m;y/=m;}if(m>=WAR_RULES.aimDeadZone){f.aimX=x/m;f.aimY=y/m;f.facing=Math.atan2(f.aimY,f.aimX);}}
  if(typeof d.aiming==="boolean"){ if(d.aiming&&f.recovery<=0&&Math.hypot(f.aimX,f.aimY)>.5){f.aiming=true;} else if(!d.aiming){f.aiming=false;f.aimHeld=0;} }
  if(typeof d.release==="number"&&Number.isFinite(d.release)&&d.release!==f.lastRelease){f.lastRelease=d.release;if(f.aiming&&f.aimHeld>=WAR_RULES.minHold&&f.recovery<=0){attack(s,f);}f.aiming=false;f.aimHeld=0;}
}
function attack(s:WarState,f:Fighter){f.protectedFor=0;if(f.role==="archer"){if(s.arrows.length<WAR_RULES.maxArrows)s.arrows.push({owner:f.id,team:f.team,x:f.x+f.aimX*30,y:f.y+f.aimY*30,vx:f.aimX*WAR_RULES.arrowSpeed,vy:f.aimY*WAR_RULES.arrowSpeed,life:2.2});f.recovery=WAR_RULES.arrowRecovery;emit(s,"arrow",f.id);}else{f.attackFor=.18;f.recovery=WAR_RULES.thrustRecovery;emit(s,"thrust",f.id);if(s.phase==="live")for(const target of s.fighters){if(target.team===f.team||target.deadFor>0||target.protectedFor>0)continue;const dx=target.x-f.x,dy=target.y-f.y,dist=Math.hypot(dx,dy),dot=(dx*f.aimX+dy*f.aimY)/Math.max(1,dist);if(dist<WAR_RULES.thrustReach&&dot>.48){damage(s,target,f,f.aimX,f.aimY);break;}}}}
function damage(s:WarState,target:Fighter,source:Fighter,nx:number,ny:number){target.health--;target.vx+=nx*105;target.vy+=ny*105;source.hits++;particles(s,target.x,target.y,TEAM[target.team].light,10);emit(s,"hit",target.id);if(target.health<=0){target.deaths++;target.deadFor=WAR_RULES.respawn;target.aiming=false;target.moveX=target.moveY=0;}}
function stepArrows(s:WarState,dt:number){for(const a of s.arrows){a.x+=a.vx*dt;a.y+=a.vy*dt;a.life-=dt;if(OBSTACLES.some(o=>a.x>o.x-o.w/2&&a.x<o.x+o.w/2&&a.y>o.y-o.h/2&&a.y<o.y+o.h/2)){a.life=0;continue;}if(s.phase!=="live")continue;for(const target of s.fighters){if(a.life<=0||target.team===a.team||target.deadFor>0||target.protectedFor>0)continue;const dx=a.x-target.x,dy=a.y-target.y;if(Math.hypot(dx,dy)>25)continue;const front=Math.cos(Math.atan2(-a.vy,-a.vx)-target.facing);if(target.role==="soldier"&&target.aiming&&target.recovery<=0&&front>.35){a.life=0;target.blocks++;particles(s,a.x,a.y,"#fff0a8",13);emit(s,"block",target.id);}else{a.life=0;const owner=s.fighters.find(f=>f.id===a.owner);if(owner)damage(s,target,owner,a.vx/WAR_RULES.arrowSpeed,a.vy/WAR_RULES.arrowSpeed);} }}s.arrows=s.arrows.filter(a=>a.life>0&&Math.abs(a.x)<900&&Math.abs(a.y)<520);}
function setBattleWinner(s:WarState){const winner=s.scores[0]===s.scores[1]?null:s.scores[0]>s.scores[1]?0:1;if(winner!==null)s.wins[winner]++;s.phase=(s.battle>=3||s.wins[0]>=2||s.wins[1]>=2)?"set-result":"battle-result";s.phaseTime=0;emit(s,"victory");if(s.phase==="set-result")s.finished=true;}
export function stepWarState(s:WarState,dt:number){dt=clamp(dt,0,.05);s.phaseTime+=dt;s.goFlash=Math.max(0,s.goFlash-dt);for(const p of s.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;}s.particles=s.particles.filter(p=>p.life>0);
  if(s.phase==="practice"&&s.phaseTime>=WAR_RULES.practice){s.phase="countdown";s.phaseTime=0;resetBattle(s);emit(s,"countdown");}
  else if(s.phase==="countdown"){const beat=Math.floor(s.phaseTime);if(beat>0&&beat<4&&Math.floor(s.phaseTime-dt)!==beat)emit(s,"countdown");if(s.phaseTime>=WAR_RULES.runway-WAR_RULES.practice){s.phase="live";s.phaseTime=0;s.goFlash=.7;emit(s,"go");}}
  else if(s.phase==="battle-result"&&s.phaseTime>=WAR_RULES.battleFinish){s.battle++;s.phase="countdown";s.phaseTime=0;resetBattle(s);emit(s,"countdown");}
  if(s.phase==="live"){s.liveTime+=dt;const next=s.liveTime>=60?2:s.liveTime>=30?1:0;if(next!==s.objectiveIndex){s.objectiveIndex=next;emit(s,"banner");}else for(const threshold of [25,55])if(s.liveTime-dt<threshold&&s.liveTime>=threshold)emit(s,"banner");if(s.liveTime>=WAR_RULES.battle)setBattleWinner(s);}
  for(const f of s.fighters){f.recovery=Math.max(0,f.recovery-dt);f.attackFor=Math.max(0,f.attackFor-dt);if(f.deadFor>0){f.deadFor=Math.max(0,f.deadFor-dt);if(f.deadFor===0){spawn(f,true);emit(s,"respawn",f.id);}continue;}f.protectedFor=Math.max(0,f.protectedFor-dt);if(f.aiming)f.aimHeld+=dt;const slow=f.aiming?(f.role==="soldier"?WAR_RULES.soldierBrace:WAR_RULES.archerDraw):1;f.vx=f.moveX*WAR_RULES.moveSpeed*slow;f.vy=f.moveY*WAR_RULES.moveSpeed*slow;const oldX=f.x,oldY=f.y;f.x=clamp(f.x+f.vx*dt,-765,765);f.y=clamp(f.y+f.vy*dt,-390,390);if(OBSTACLES.some(o=>f.x>o.x-o.w/2-24&&f.x<o.x+o.w/2+24&&f.y>o.y-o.h/2-24&&f.y<o.y+o.h/2+24)){f.x=oldX;f.y=oldY;}if(Math.hypot(f.moveX,f.moveY)>.1&&!f.aiming)f.facing=Math.atan2(f.moveY,f.moveX);const site=SITES[s.objectiveIndex];if(f.protectedFor>0&&Math.hypot(f.x-site.x,f.y-site.y)<WAR_RULES.objectiveRadius)f.protectedFor=0;}
  for(let i=0;i<s.fighters.length;i++)for(let j=i+1;j<s.fighters.length;j++){const a=s.fighters[i],b=s.fighters[j];if(a.deadFor||b.deadFor||a.protectedFor||b.protectedFor)continue;const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d>0&&d<43){const push=(43-d)*.09;a.x-=dx/d*push;b.x+=dx/d*push;a.y-=dy/d*push;b.y+=dy/d*push;}}
  stepArrows(s,dt);
  if(s.phase==="live"){const site=SITES[s.objectiveIndex],inside:[boolean,boolean]=[false,false];for(const f of s.fighters)if(f.deadFor<=0&&f.protectedFor<=0&&Math.hypot(f.x-site.x,f.y-site.y)<WAR_RULES.objectiveRadius){inside[f.team]=true;f.contest+=dt;}if(inside[0]&&!inside[1])s.scores[0]+=dt;if(inside[1]&&!inside[0])s.scores[1]+=dt;}
}
function uneven(s:WarState){return s.fighters.filter(f=>f.team===0).length!==s.fighters.filter(f=>f.team===1).length}

export function warPhoneFrame(s:WarState,f:Fighter):WarPhoneFrame { const remaining=s.phase==="live"?WAR_RULES.battle-s.liveTime:s.phase==="practice"?WAR_RULES.practice-s.phaseTime:s.phase==="countdown"?WAR_RULES.runway-WAR_RULES.practice-s.phaseTime:s.phase==="battle-result"?WAR_RULES.battleFinish-s.phaseTime:0;return {t:"warState",phase:f.deadFor>0?"respawning":s.phase,role:f.role,team:f.team,interactive:s.phase==="practice"||s.phase==="live",status:f.deadFor>0?`RETURNING · ${Math.ceil(f.deadFor)}`:s.phase==="practice"?"PRACTICE · CHOOSE YOUR CLASS":s.phase==="countdown"?`READY · ${Math.max(1,Math.ceil(remaining))}`:s.phase==="live"?(f.protectedFor>0?"SPAWN SHIELD · MOVE IN":"MOVE · AIM · RELEASE"):s.phase==="battle-result"?"CHANGE CLASS FOR NEXT BATTLE":"WAR COMPLETE",health:f.health,maxHealth:healthFor(f.role),remaining:Math.max(0,remaining),battle:s.battle,wins:[...s.wins],uneven:uneven(s)}; }
export function isWarPhoneFrame(v:unknown):v is WarPhoneFrame {if(!v||typeof v!=="object"||Array.isArray(v))return false;const f=v as WarPhoneFrame;return f.t==="warState"&&["practice","countdown","live","battle-result","set-result","respawning","spectating"].includes(f.phase)&&["soldier","archer"].includes(f.role)&&[0,1].includes(f.team)&&Number.isFinite(f.health)&&Number.isFinite(f.remaining)&&Array.isArray(f.wins)&&(f.cues===undefined||f.cues.every(isWarCue));}

function roundRect(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){c.beginPath();c.roundRect(x,y,w,h,r);}
function text(c:CanvasRenderingContext2D,value:string,x:number,y:number,size:number,align:CanvasTextAlign="center",color:string="#f9eed8"){c.save();c.textAlign=align;c.textBaseline="middle";c.font=`900 ${size}px system-ui, sans-serif`;c.lineWidth=Math.max(3,size*.12);c.strokeStyle="#211c18";c.strokeText(value,x,y);c.fillStyle=color;c.fillText(value,x,y);c.restore();}
function drawGround(c:CanvasRenderingContext2D,w:number,h:number){c.fillStyle="#cfa96f";c.fillRect(0,0,w,h);c.save();c.globalAlpha=.16;c.fillStyle="#382a20";for(let i=0;i<70;i++){const x=(i*317)%w,y=(i*173)%h;c.beginPath();c.arc(x,y,1+(i%3),0,Math.PI*2);c.fill();}c.restore();}
function toScreen(w:number,h:number,x:number,y:number){const scale=Math.min(w/1700,(h-90)/900);return{x:w/2+x*scale,y:90+(h-90)/2+y*scale,s:scale};}
function drawFighter(c:CanvasRenderingContext2D,w:number,h:number,f:Fighter,s:WarState){const p=toScreen(w,h,f.x,f.y),scale=p.s,angle=f.facing; c.save();c.translate(p.x,p.y);c.scale(scale,scale);c.rotate(angle);if(f.deadFor>0){c.globalAlpha=.45;c.rotate(-1.2);}
  if(f.protectedFor>0){c.strokeStyle="#fff3bd";c.lineWidth=5;c.setLineDash([8,6]);c.beginPath();c.arc(0,0,31,0,Math.PI*2);c.stroke();c.setLineDash([]);}
  const team=TEAM[f.team];c.fillStyle="#201b18";c.beginPath();if(f.role==="soldier")c.arc(0,0,25,0,Math.PI*2);else{c.moveTo(27,0);c.lineTo(-12,-22);c.lineTo(-20,0);c.lineTo(-12,22);c.closePath();}c.fill();c.fillStyle=team.color;c.beginPath();if(f.role==="soldier")c.arc(0,0,21,0,Math.PI*2);else{c.moveTo(23,0);c.lineTo(-10,-18);c.lineTo(-16,0);c.lineTo(-10,18);c.closePath();}c.fill();
  if(f.role==="soldier"){const guard=f.aiming&&f.recovery<=0;c.fillStyle="#292522";c.beginPath();c.ellipse(guard?22:3,guard?0:18,8,25,0,0,Math.PI*2);c.fill();c.strokeStyle="#eee0c4";c.lineWidth=4;c.beginPath();c.moveTo(6,guard?8:3);c.lineTo((f.attackFor>0?78:46),guard?8:3);c.stroke();}else{c.strokeStyle="#291f19";c.lineWidth=4;c.beginPath();c.arc(10,0,25,-1.2,1.2);c.stroke();c.beginPath();c.moveTo(19,-23);c.lineTo(f.aiming?-5:14,0);c.lineTo(19,23);c.stroke();}
  c.rotate(-angle);c.fillStyle="#211c18";c.beginPath();c.arc(0,-37,13,0,Math.PI*2);c.fill();c.fillStyle=f.color;c.beginPath();c.arc(0,-37,9,0,Math.PI*2);c.fill();c.fillStyle="#fff";c.font="900 12px system-ui";c.textAlign="center";c.textBaseline="middle";c.fillText(String(f.seat+1),0,-37);c.restore();
  text(c,f.name.toUpperCase().slice(0,10),p.x,p.y-53*scale,14*scale);for(let i=0;i<healthFor(f.role);i++){c.fillStyle=i<f.health?TEAM[f.team].light:"#4e4035";c.beginPath();c.arc(p.x+(i-(healthFor(f.role)-1)/2)*13*scale,p.y-35*scale,4.5*scale,0,Math.PI*2);c.fill();}if(f.deadFor>0)text(c,String(Math.ceil(f.deadFor)),p.x,p.y,25*scale);}
export function renderWar(s:WarState,c:CanvasRenderingContext2D,w:number,h:number){drawGround(c,w,h);for(const o of OBSTACLES){const q=toScreen(w,h,o.x,o.y);c.fillStyle="#3b332b";c.strokeStyle="#81705c";c.lineWidth=5*q.s;roundRect(c,q.x-o.w*q.s/2,q.y-o.h*q.s/2,o.w*q.s,o.h*q.s,9*q.s);c.fill();c.stroke();}const site=SITES[s.objectiveIndex],p=toScreen(w,h,site.x,site.y);c.save();c.strokeStyle=s.phase==="live"?"#fff1b7":"#705c43";c.lineWidth=8*p.s;c.setLineDash([18*p.s,9*p.s]);c.beginPath();c.arc(p.x,p.y,WAR_RULES.objectiveRadius*p.s,0,Math.PI*2);c.stroke();c.setLineDash([]);c.fillStyle="rgba(255,239,176,.13)";c.fill();c.strokeStyle="#30261e";c.lineWidth=7*p.s;c.beginPath();c.moveTo(p.x,p.y+38*p.s);c.lineTo(p.x,p.y-55*p.s);c.stroke();c.fillStyle=TEAM[(s.objectiveIndex+s.battle)%2 as 0|1].color;c.beginPath();c.moveTo(p.x,p.y-55*p.s);c.lineTo(p.x+52*p.s,p.y-38*p.s);c.lineTo(p.x,p.y-19*p.s);c.fill();c.restore();
  for(const a of s.arrows){const q=toScreen(w,h,a.x,a.y);c.save();c.translate(q.x,q.y);c.rotate(Math.atan2(a.vy,a.vx));c.strokeStyle=TEAM[a.team].light;c.lineWidth=4*q.s;c.beginPath();c.moveTo(-16*q.s,0);c.lineTo(16*q.s,0);c.stroke();c.restore();}for(const f of s.fighters)drawFighter(c,w,h,f,s);for(const x of s.particles){const q=toScreen(w,h,x.x,x.y);c.globalAlpha=clamp(x.life*3,0,1);c.fillStyle=x.color;c.fillRect(q.x,q.y,4*q.s,4*q.s);}c.globalAlpha=1;
  c.fillStyle="#211c18";c.fillRect(0,0,w,88);text(c,`${TEAM[0].shape} ${Math.floor(s.scores[0])}`,w*.16,43,39,"center",TEAM[0].light);text(c,`${Math.max(0,Math.ceil(WAR_RULES.battle-s.liveTime))}`,w*.5,32,42);text(c,`${Math.floor(s.scores[1])} ${TEAM[1].shape}`,w*.84,43,39,"center",TEAM[1].light);text(c,`BATTLE ${s.battle}  ·  ${s.wins[0]}—${s.wins[1]}`,w*.5,68,16);if(uneven(s))text(c,"PLAYTEST · UNEVEN TEAMS",w*.5,h-24,19,"center","#fff0a8");
  const untilMove=s.objectiveIndex===0?30-s.liveTime:s.objectiveIndex===1?60-s.liveTime:99;if(s.phase==="live"&&untilMove<=5&&untilMove>0){const next=toScreen(w,h,SITES[s.objectiveIndex+1].x,SITES[s.objectiveIndex+1].y);c.save();c.strokeStyle="#332b24";c.lineWidth=4;c.setLineDash([10,8]);c.beginPath();c.arc(next.x,next.y,WAR_RULES.objectiveRadius*next.s,0,Math.PI*2);c.stroke();c.restore();text(c,`NEXT IN ${Math.ceil(untilMove)}`,next.x,next.y,18);}
  let overlay:string|null=null,sub="";if(s.phase==="practice"){overlay="MOVE · AIM · RELEASE";sub=`HARMLESS PRACTICE  ·  CHOOSE CLASS  ·  ${Math.ceil(WAR_RULES.practice-s.phaseTime)}`;}else if(s.phase==="countdown"){const left=WAR_RULES.runway-WAR_RULES.practice-s.phaseTime;overlay=left<1?"GO!":String(Math.max(1,Math.ceil(left)));sub="GROUND AND DAMAGE START TOGETHER";}else if(s.phase==="battle-result"||s.phase==="set-result"){const winner=s.scores[0]===s.scores[1]?"BATTLE DRAW":`${TEAM[s.scores[0]>s.scores[1]?0:1].name} TAKES THE BANNER`;overlay=s.phase==="set-result"?(s.wins[0]===s.wins[1]?"WAR DRAW":`${TEAM[s.wins[0]>s.wins[1]?0:1].name} WINS THE WAR`):winner;sub=s.fighters.sort((a,b)=>(b.blocks+b.hits)-(a.blocks+a.hits)).slice(0,3).map(f=>`${f.name}: ${f.hits} hits · ${f.blocks} blocks`).join("    ");}if(overlay){c.fillStyle="rgba(25,20,16,.76)";roundRect(c,w*.17,h*.36,w*.66,h*.23,22);c.fill();text(c,overlay,w*.5,h*.445,Math.min(58,w*.055));text(c,sub,w*.5,h*.53,Math.min(18,w*.018));}}

export function warResults(s:WarState):RoundResult[]{const winning=s.wins[0]===s.wins[1]?null:s.wins[0]>s.wins[1]?0:1;return s.fighters.filter(f=>s.participantIds.has(f.id)).map(f=>({id:f.id,place:winning===null?1:f.team===winning?1:2,score:winning===null?2:f.team===winning?3:1,detail:`${TEAM[f.team].name} · ${f.hits} hits · ${f.blocks} blocks · ${Math.round(f.contest)}s contest`})).sort((a,b)=>a.place-b.place);}
export function createHost(ctx:HostContext):GameHost {const queued:Player[]=[];let observedBattle=1;const reduced=typeof matchMedia!=="undefined"&&matchMedia("(prefers-reduced-motion: reduce)").matches;const s=createWarState(ctx.players,ctx.seed,reduced);let sound:WarSound|null=null;try{sound=new WarSound("host");}catch{/* audio is optional */}function flush(){const frames:Record<string,WarPhoneFrame>={};for(const f of s.fighters)frames[f.id]={...warPhoneFrame(s,f),cues:s.events.filter(e=>!e.to||e.to===f.id).map(e=>e.cue)};ctx.send({t:"warStates",frames} satisfies WarPhoneFrames);for(const e of s.events)sound?.play(e.cue);s.events=[];}return{onJoin(p){queued.push(p);const base=s.fighters[0]?warPhoneFrame(s,s.fighters[0]):null;if(base)ctx.send({...base,phase:"spectating",status:"JOINING NEXT BATTLE",interactive:false,role:"soldier",team:(s.fighters.length%2) as 0|1},p.id);},onInput(id,d){if(d&&typeof d==="object"&&!Array.isArray(d)&&(d as WarInput).sync){const f=s.fighters.find(x=>x.id===id);if(f)ctx.send(warPhoneFrame(s,f),id);return;}applyWarInput(s,id,d);},onConnectionChange(id,connected){const f=s.fighters.find(x=>x.id===id);if(f){f.connected=connected;if(!connected)cancelWarInput(f);}},onLeave(id){const f=s.fighters.find(x=>x.id===id);if(f)cancelWarInput(f);},tick(dt){stepWarState(s,dt);if(s.battle!==observedBattle){observedBattle=s.battle;while(queued.length){const p=queued.shift()!;s.fighters.push(makeFighter(p,s.fighters.length));}}s.phoneClock+=dt;if(s.phoneClock>=.2||s.events.length){s.phoneClock=0;flush();}},render(c,w,h){renderWar(s,c,w,h);},isOver(){return s.finished&&s.phaseTime>=WAR_RULES.battleFinish;},results(){return warResults(s);},destroy(){sound?.destroy();sound=null;}};}
